### ISSUE TITLE
Error buying token: Error: fetch failed

### ISSUE THREAD

**Issue by Ytu-str** [Al366io/solana-transactions-wrapper#10]

**Comment by Al366io** [comment]
Could you please provide more information? 
A little hard to help like this 😁

**Comment by Ytu-str** [comment]
Thanks for your reply, the program can run normally,But I had a problem:The probability of a correct transaction being completed is very low,Many cases are not stuck at the last one.Is it caused by the network problem of jup? What are the good solutions?

**Comment by Ytu-str** [comment]
Been waiting for confirmation

**Comment by Al366io** [comment]
When I implemented the package, the % of successful transactions was over 95% with default settings.
If you are changing the slippage, that could be the first thing i would look into! Default value is `1%`

If not, i'd still play with that value a bit to find the perfect tweak for your needs. Another thing worth noticing is that the package defaults the network fees to "auto" which is an automatic value Jupiter sets. Could be good trying to higher these two values and see if it increases your % of succeeded transactions!

- I'll open an Issue to make the `prioritizationFeeLamports` variable modifiable in the buy / sell functions. Feel free to take it and open a PR

**Comment by Al366io** [comment]
added #11

**Comment by Ytu-str** [comment]
Can you tell me which RPC ENDPOINT you're using?

**Comment by Al366io** [comment]
[Quicknode](https://www.quicknode.com/docs/solana)
