### ISSUE TITLE
No exported member "buy_token"

### ISSUE THREAD

**Issue by jrmcdona** [Al366io/solana-transactions-wrapper#13]
![image](https://github.com/Al366io/solana-transactions-wrapper/assets/4327773/c88ad2c3-37bd-487c-abbe-c00aeaea5040)

I find this to be very odd.   I deleted all node_modules and restarted vs code but stil an issue.   

I have these settings.  I have tried npm install several times but not fixing the issues. 

    "target": "es2016",     
    "module": "commonjs", 

What do you think is the problem?

**Comment by Al366io** [comment]
That's interesting - looks more like a vscode / ts problem to me, if you npm install the package the exported functions must be there!

Did you already fix this by any chance? Saw you posted another issue so maybe this one's resolved already?

**Comment by jrmcdona** [comment]
@Al366io   nope!  This doesn't work for me.   No clue why.   Not have any issues with any other packages I have installed.

I end up having to copy over your source code.

**Comment by jrmcdona** [comment]
@Al366io   by the way do you hit a lot of block height issues?

**Comment by Al366io** [comment]
Ye that's strange cause everybody else is using it without problems ahah
try in a js file - I have a feeling it's TS that's complaining cause those methods are not exported in the `types.d.ts`

As for you question, idk, I don't operate, just built this for the community 👍🏼
