### ISSUE TITLE
Error processing Instruction 3: custom program error: 0x1

### ISSUE THREAD

**Issue by L2b2n** [Al366io/solana-transactions-wrapper#4]
Connection established 🚀
Wallet fetched ✅
Trying to buy token using 0.01 SOL...

Error: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 3: custom program error: 0x1
    at C:\Users\tobib\Desktop\volumen-bot\node_modules\solana-transactions-wrapper\dist\index.js:39:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\tobib\Desktop\volumen-bot\node_modules\solana-transactions-wrapper\dist\index.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Al366io** [comment]
Hi ! 
from a quick look, looks like you don't have enough funds 

https://solana.stackexchange.com/questions/1282/transaction-simulation-failed-failed-to-send-transaction-transaction-simulatio

**Comment by Al366io** [comment]
Also, debugging tip, if you search for your wallet public address in solscan, you can locate the transaction, access it and see what's the error. Example with a transaction that has the same error as yours:

https://explorer.solana.com/tx/7GJVokV3YWZ3LFVZtv1Nwp6BGKr9wcLR6CzrLdTyy9QdNF7DaW5bmQzMm3PcPf2djNx39m6f1ccH97SNsmVoZr3

Closing this 👍🏼
