### ISSUE TITLE
What the best node for this ? 

### ISSUE THREAD

**Issue by L2b2n** [Al366io/solana-transactions-wrapper#5]
Error: SolanaJSONRPCError: failed to get accounts owned by program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA excluded from account secondary indexes; this RPC method unavailable for key
    at C:\Users\tobib\Desktop\volumen-bot\node_modules\solana-transactions-wrapper\dist\walletInfo.js:53:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\tobib\Desktop\volumen-bot\node_modules\solana-transactions-wrapper\dist\walletInfo.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

i have alchemy

**Comment by Al366io** [comment]
i don't think you can get accounts of a token program - not with the method i implemented 
im sure there's some method in [@solana/web3.js](https://www.npmjs.com/package/%40solana%2Fweb3.js) to do that

**Comment by L2b2n** [comment]
thx will check
